# Generated by Django 4.0 on 2021-12-28 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_user_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='id_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.email'),
        ),
    ]
