# Generated by Django 4.0 on 2021-12-29 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_pessoa_id_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel_instituicao',
            name='id_instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.pessoa'),
        ),
    ]
