# Generated by Django 4.0 on 2021-12-29 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_relatorios_respostas_id_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostas',
            name='id_relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.relatorios'),
        ),
    ]
