# Generated by Django 4.0 on 2021-12-29 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_respostas_id_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorios',
            name='id_dimensao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.dimensoes'),
        ),
    ]
