# Generated by Django 4.0 on 2021-12-29 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_relatorios_id_dimensao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorios',
            name='id_dimensao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.dimensoes'),
        ),
    ]
