# Generated by Django 4.0.2 on 2022-05-09 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('desativar', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Anos Base',
            },
        ),
        migrations.CreateModel(
            name='Dimensoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Dimensão')),
                ('descricao', models.TextField(verbose_name='Descrição da Dimensão')),
                ('desativar', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Dimensões',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Município')),
                ('desativar', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, null=True, verbose_name='CPF')),
                ('nome_social', models.CharField(blank=True, max_length=256, verbose_name='Nome Social')),
                ('desativar', models.BooleanField()),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.municipio', verbose_name='Município')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name_plural': 'Pessoas Físicas',
            },
        ),
        migrations.CreateModel(
            name='Pessoa_juridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=50, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=256, verbose_name='Razão Social')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('desativar', models.BooleanField()),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.municipio', verbose_name='Município')),
            ],
            options={
                'verbose_name_plural': 'Pessoas Jurídicas',
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Região Geográfica')),
                ('desativar', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Regiões',
            },
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desativar', models.BooleanField()),
                ('id_ano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.ano_base', verbose_name='Ano')),
                ('id_dimensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.dimensoes', verbose_name='Dimensão')),
                ('id_pessoa_juridica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pessoa_juridica', verbose_name='Instituição')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='Tipo_esfera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Tipo Esfera')),
                ('desativar', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Tipos de Esferas',
            },
        ),
        migrations.CreateModel(
            name='Variavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Variável')),
                ('descricao', models.TextField(verbose_name='Descrição da Variável')),
                ('tag', models.CharField(max_length=50, verbose_name='#TAG')),
                ('desativar', models.BooleanField()),
                ('id_dimensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.dimensoes', verbose_name='Dimensão')),
            ],
            options={
                'verbose_name_plural': 'Variáveis',
            },
        ),
        migrations.CreateModel(
            name='Uf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Estado')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla UF')),
                ('desativar', models.BooleanField()),
                ('id_regiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.regiao', verbose_name='Região Geográfica')),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Sub_indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Sub-Indicador')),
                ('descricao', models.TextField(verbose_name='Descrição do Sub-Indicador')),
                ('desativar', models.BooleanField()),
                ('id_dimensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.dimensoes', verbose_name='Dimensão')),
            ],
            options={
                'verbose_name_plural': 'Sub Indicadores',
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=256, verbose_name='Resposa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima alteração')),
                ('tag', models.CharField(max_length=50, verbose_name='#TAG')),
                ('desativar', models.BooleanField()),
                ('id_ano_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.ano_base', verbose_name='Ano')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='cadastros.pessoa', verbose_name='Responsável')),
                ('id_pessoa_juridica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituicao', to='cadastros.pessoa_juridica', verbose_name='Instituição')),
                ('id_relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.relatorios', verbose_name='Relatório')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('id_variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.variavel', verbose_name='Variável')),
            ],
            options={
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='Responsavel_instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desativar', models.BooleanField()),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pessoa', verbose_name='Pessoa Responsável')),
                ('id_pessoa_juridica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pessoa_juridica', verbose_name='Instituição')),
            ],
            options={
                'verbose_name_plural': 'Responsáveis Instituição',
            },
        ),
        migrations.AddField(
            model_name='pessoa_juridica',
            name='id_tipo_esfera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipo_esfera', verbose_name='Tipo Esfera'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='id_uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.uf', verbose_name='UF'),
        ),
        migrations.CreateModel(
            name='Grupo_variavel_subind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desativar', models.BooleanField()),
                ('id_dimensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.dimensoes', verbose_name='Dimensões')),
                ('id_sub_indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.sub_indicadores', verbose_name='Indicadores')),
                ('id_variavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.variavel', verbose_name='Variável')),
            ],
            options={
                'verbose_name_plural': 'Grupo_variavel_subind',
            },
        ),
    ]
