# Generated by Django 4.0.4 on 2022-05-10 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='sub_indicadores',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Sub-Indicador'),
        ),
    ]
