# Generated by Django 4.0 on 2021-12-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostas',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
