# Generated by Django 4.0.4 on 2022-05-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_pessoa_options_alter_relatorios_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostas',
            name='id_dimensao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.dimensoes', verbose_name='Dimensão'),
        ),
    ]
