# Generated by Django 4.0 on 2021-12-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_respostas_data_atualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('id_pessoa', models.IntegerField()),
                ('_delete', models.BooleanField()),
            ],
        ),
    ]
