# Generated by Django 4.0.4 on 2022-05-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_respostas_id_dimensao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostas',
            name='id_dimensao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.dimensoes', verbose_name='Dimensão'),
        ),
    ]
