# Generated by Django 4.0 on 2021-12-29 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_responsavel_instituicao_id_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel_instituicao',
            name='id_instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituicao', to='cadastros.pessoa'),
        ),
        migrations.AlterField(
            model_name='responsavel_instituicao',
            name='id_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='cadastros.pessoa'),
        ),
    ]
