# Generated by Django 4.0.4 on 2022-05-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_respostas_id_subindicador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostas',
            name='resposta',
            field=models.FloatField(verbose_name='Resposa'),
        ),
    ]
