# Generated by Django 4.0.4 on 2022-05-17 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_respostas_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoSubIndicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome Grupo Sub-Indicadorer')),
                ('descricao', models.TextField(verbose_name='Descrição do Grupo Sub-indicadores')),
                ('desativar', models.BooleanField()),
                ('id_dimensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.dimensoes', verbose_name='Dimensão')),
            ],
            options={
                'verbose_name_plural': 'Gupos_Sub_Indicadores',
            },
        ),
    ]
