# Generated by Django 4.0.4 on 2022-05-18 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_gruposubindicadores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo_variavel_subind',
            options={'verbose_name_plural': 'Grupo Variável Sub-indicadores'},
        ),
        migrations.AlterModelOptions(
            name='gruposubindicadores',
            options={'verbose_name_plural': 'Gupos Sub-Indicadores'},
        ),
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Indicador')),
                ('descricao', models.TextField(verbose_name='Descrição do Indicador')),
                ('desativar', models.BooleanField()),
                ('id_dimensao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.dimensoes', verbose_name='Dimensão')),
            ],
            options={
                'verbose_name_plural': 'Indicadores',
            },
        ),
        migrations.AlterField(
            model_name='grupo_variavel_subind',
            name='id_sub_indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.indicadores', verbose_name='Indicadores'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='id_subindicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.indicadores', verbose_name='Sub-Indicador'),
        ),
        migrations.DeleteModel(
            name='Sub_indicadores',
        ),
    ]
