# Generated by Django 4.0.4 on 2022-05-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_grupo_variavel_subind_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostas',
            name='id_subindicador',
        ),
        migrations.AddField(
            model_name='respostas',
            name='id_indicador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastros.indicadores', verbose_name='Indicador'),
            preserve_default=False,
        ),
    ]
