# Generated by Django 4.0.4 on 2022-05-18 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_remove_respostas_id_subindicador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadores',
            name='id_variavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.variavel', verbose_name='Variável'),
            preserve_default=False,
        ),
    ]
