# Generated by Django 4.0.2 on 2022-05-04 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0011_alter_relatorios_id_dimensao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=50, verbose_name='CPF')),
                ('nome_social', models.CharField(blank=True, max_length=256, verbose_name='Nome Social')),
                ('_delete', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Pessoas Físicas',
            },
        ),
        migrations.CreateModel(
            name='PJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=50, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=256, verbose_name='Razão Social')),
                ('_delete', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Pessoas Jurídicas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_esfera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Tipo Esfera')),
                ('_delete', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Tipos de Esferas',
            },
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='id_email',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='id_tipo_pessoa',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='id_uf',
        ),
        migrations.AlterModelOptions(
            name='ano_base',
            options={'verbose_name_plural': 'Anos Base'},
        ),
        migrations.AlterModelOptions(
            name='dimensoes',
            options={'verbose_name_plural': 'Dimensões'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': 'Emails'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name_plural': 'Municípios'},
        ),
        migrations.AlterModelOptions(
            name='regiao',
            options={'verbose_name_plural': 'Regiões'},
        ),
        migrations.AlterModelOptions(
            name='relatorios',
            options={'verbose_name_plural': 'Relatórios'},
        ),
        migrations.AlterModelOptions(
            name='responsavel_instituicao',
            options={'verbose_name_plural': 'Responsáveis Instituição'},
        ),
        migrations.AlterModelOptions(
            name='respostas',
            options={'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterModelOptions(
            name='sub_indicadores',
            options={'verbose_name_plural': 'Sub Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='uf',
            options={'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='user_pessoa',
            options={'verbose_name_plural': 'Users_Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='variavel',
            options={'verbose_name_plural': 'Variáveis'},
        ),
        migrations.AddField(
            model_name='relatorios',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ano_base',
            name='ano',
            field=models.PositiveIntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='dimensoes',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da Dimensão'),
        ),
        migrations.AlterField(
            model_name='dimensoes',
            name='nome',
            field=models.CharField(max_length=256, verbose_name='Dimensão'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='id_uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.uf', verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='regiao',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Região Geográfica'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='id_ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.ano_base', verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='id_dimensao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.dimensoes', verbose_name='Dimensão'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima alteração'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='data_resposta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='id_ano_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.ano_base', verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='id_relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.relatorios', verbose_name='Relatório'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='id_variavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.variavel', verbose_name='Variável'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='resposta',
            field=models.CharField(max_length=256, verbose_name='Resposa'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='tag',
            field=models.CharField(max_length=50, verbose_name='#TAG'),
        ),
        migrations.AlterField(
            model_name='sub_indicadores',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Sub-Indicador'),
        ),
        migrations.AlterField(
            model_name='sub_indicadores',
            name='id_dimensao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.dimensoes', verbose_name='Dimensão'),
        ),
        migrations.AlterField(
            model_name='sub_indicadores',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Sub-Indicador'),
        ),
        migrations.AlterField(
            model_name='uf',
            name='id_regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.regiao', verbose_name='Região Geográfica'),
        ),
        migrations.AlterField(
            model_name='uf',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='uf',
            name='sigla',
            field=models.CharField(max_length=2, verbose_name='Sigla UF'),
        ),
        migrations.AlterField(
            model_name='user_pessoa',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='variavel',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da Variável'),
        ),
        migrations.AlterField(
            model_name='variavel',
            name='id_dimensao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.dimensoes', verbose_name='Dimensão'),
        ),
        migrations.AlterField(
            model_name='variavel',
            name='nome',
            field=models.CharField(max_length=256, verbose_name='Variável'),
        ),
        migrations.AlterField(
            model_name='variavel',
            name='tag',
            field=models.CharField(max_length=50, verbose_name='#TAG'),
        ),
        migrations.DeleteModel(
            name='Tipo_pessoa',
        ),
        migrations.AddField(
            model_name='pj',
            name='id_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.email', verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='pj',
            name='id_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.municipio', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='pj',
            name='id_tipo_esfera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipo_esfera', verbose_name='Tipo Esfera'),
        ),
        migrations.AddField(
            model_name='pj',
            name='id_uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.uf', verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='pf',
            name='id_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.email', verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='id_instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pj', verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='responsavel_instituicao',
            name='id_instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pj', verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='responsavel_instituicao',
            name='id_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pf', verbose_name='Nome do Responsável'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='id_instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituicao', to='cadastros.pj', verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='id_respondido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='cadastros.pf', verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='user_pessoa',
            name='id_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.pf', verbose_name='Nome do Usuário'),
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
