# Generated by Django 4.0.4 on 2022-05-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_grupoindicadores_delete_gruposubindicadores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupo_variavel_subind',
        ),
    ]
