# Generated by Django 4.0.2 on 2022-05-05 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0012_pf_pj_tipo_esfera_remove_pessoa_id_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pf',
            name='cpf',
            field=models.CharField(max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user_pessoa',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
