# Generated by Django 4.0.4 on 2022-05-18 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_delete_grupo_variavel_subind'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoindicadores',
            name='id_indicador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.indicadores', verbose_name='Indicador'),
            preserve_default=False,
        ),
    ]
