# Generated by Django 4.0.4 on 2022-05-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_grupoindicadores_id_indicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicadores',
            name='id_variavel',
        ),
        migrations.AddField(
            model_name='variavel',
            name='id_indicador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.indicadores', verbose_name='Indicador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupoindicadores',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Grupo Indicadores'),
        ),
    ]
