# Generated by Django 4.0.4 on 2022-05-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_remove_indicadores_id_variavel_variavel_id_indicador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoindicadores',
            name='id_indicador',
        ),
    ]
