# Generated by Django 4.0.4 on 2022-05-18 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_remove_grupoindicadores_id_indicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadores',
            name='id_grupoindicadores',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.grupoindicadores', verbose_name='Grupo Indicador'),
            preserve_default=False,
        ),
    ]
