# Generated by Django 4.0.4 on 2022-05-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_indicadores_id_grupoindicadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='variavel',
            name='id_grupoindicador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.grupoindicadores', verbose_name='Grupo Idicador'),
            preserve_default=False,
        ),
    ]
