# Generated by Django 4.0.4 on 2022-05-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_variavel_id_grupoindicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostas',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='variavel',
            name='tag',
        ),
    ]
